// 官方标准参数白名单（最低集 = haru.cdi3.json 32 参数 + 常用扩展）
// 规范同步源：specs/standard-params.json（测试断言两者一致）
export const STANDARD_PARAMS: readonly string[] = [
  "PARAM_ANGLE_X","PARAM_ANGLE_Y","PARAM_ANGLE_Z",
  "PARAM_EYE_L_OPEN","PARAM_EYE_L_SMILE","PARAM_EYE_R_OPEN","PARAM_EYE_R_SMILE",
  "PARAM_EYE_FORM","PARAM_EYE_BALL_X","PARAM_EYE_BALL_Y","PARAM_EYE_BALL_FORM",
  "PARAM_BROW_L_Y","PARAM_BROW_R_Y","PARAM_BROW_L_X","PARAM_BROW_R_X",
  "PARAM_BROW_L_ANGLE","PARAM_BROW_R_ANGLE","PARAM_BROW_L_FORM","PARAM_BROW_R_FORM",
  "PARAM_MOUTH_FORM","PARAM_MOUTH_OPEN_Y","PARAM_TERE",
  "PARAM_BODY_ANGLE_X","PARAM_BODY_ANGLE_Y","PARAM_BODY_ANGLE_Z",
  "PARAM_BREATH","PARAM_ARM_L_A","PARAM_ARM_R_A","PARAM_ARM_L_B","PARAM_ARM_R_B",
  "PARAM_BUST_Y","PARAM_HAIR_FRONT","PARAM_HAIR_BACK",
  // 扩展（VTube Studio/常见模型用，语义与官方一致）
  "PARAM_EYE_L_SMILE_FORM","PARAM_EYE_R_SMILE_FORM",
  "PARAM_HAIR_SIDE","PARAM_SHOULDER_ANGLE_X","PARAM_SHOULDER_ANGLE_Y","PARAM_SHOULDER_ANGLE_Z",
  "PARAM_BODY_BEND_Z","PARAM_WAIST_X","PARAM_WAIST_Y","PARAM_WAIST_Z",
] as const;

const SET = new Set<string>(STANDARD_PARAMS);

export function isStandardParam(id: string): boolean {
  return SET.has(id);
}

export const PARAM_GROUPS: Record<string, string[]> = {
  EyeBlink: ["PARAM_EYE_L_OPEN", "PARAM_EYE_R_OPEN"],
  LipSync: ["PARAM_MOUTH_OPEN_Y"],
  Head: ["PARAM_ANGLE_X", "PARAM_ANGLE_Y", "PARAM_ANGLE_Z"],
  Body: ["PARAM_BODY_ANGLE_X", "PARAM_BODY_ANGLE_Y", "PARAM_BODY_ANGLE_Z"],
  Physics: ["PARAM_BUST_Y", "PARAM_HAIR_FRONT", "PARAM_HAIR_BACK"],
};
